package org.tms.offline;

import android.content.*;
import android.database.*;
import android.database.sqlite.*;
import org.json.*;
import java.io.*;
import java.nio.*;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.text.Normalizer;
import java.util.*;
import java.util.regex.*;

public final class Store extends SQLiteOpenHelper {
 public final Context context;
 public Store(Context c){super(c.getApplicationContext(),"local-ai-v5.db",null,1);context=c.getApplicationContext();setWriteAheadLoggingEnabled(true);}
 @Override public void onConfigure(SQLiteDatabase db){db.setForeignKeyConstraintsEnabled(true);}
 @Override public void onCreate(SQLiteDatabase db){
  db.execSQL("CREATE TABLE docs(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,sha TEXT NOT NULL UNIQUE,pages INTEGER NOT NULL,bytes INTEGER NOT NULL,path TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'indexing',created INTEGER NOT NULL)");
  db.execSQL("CREATE TABLE pages(id INTEGER PRIMARY KEY AUTOINCREMENT,doc INTEGER NOT NULL REFERENCES docs(id) ON DELETE CASCADE,pageno INTEGER NOT NULL,label TEXT NOT NULL DEFAULT '',text TEXT NOT NULL,width REAL DEFAULT 612,height REAL DEFAULT 792,boxes TEXT NOT NULL DEFAULT '[]',ocr INTEGER DEFAULT 0,UNIQUE(doc,pageno))");
  db.execSQL("CREATE TABLE chunks(id INTEGER PRIMARY KEY AUTOINCREMENT,page INTEGER NOT NULL REFERENCES pages(id) ON DELETE CASCADE,doc INTEGER NOT NULL REFERENCES docs(id) ON DELETE CASCADE,text TEXT NOT NULL,vid INTEGER NOT NULL DEFAULT -1,embedding BLOB)");
  db.execSQL("CREATE INDEX chunk_doc ON chunks(doc)");db.execSQL("CREATE INDEX chunk_vid ON chunks(vid)");db.execSQL("CREATE INDEX chunk_page ON chunks(page)");
  db.execSQL("CREATE VIRTUAL TABLE chunks_fts USING fts4(body,tokenize=unicode61)");
  db.execSQL("CREATE TABLE models(id TEXT PRIMARY KEY,title TEXT NOT NULL,path TEXT NOT NULL,sha TEXT NOT NULL,bytes INTEGER NOT NULL,enabled INTEGER NOT NULL DEFAULT 0,license TEXT NOT NULL)");
  db.execSQL("CREATE TABLE history(id INTEGER PRIMARY KEY AUTOINCREMENT,question TEXT NOT NULL,payload TEXT NOT NULL,created INTEGER NOT NULL)");
  db.execSQL("CREATE TABLE meta(key TEXT PRIMARY KEY,value TEXT NOT NULL)");
 }
 @Override public void onUpgrade(SQLiteDatabase d,int a,int b){throw new IllegalStateException("Unsupported database migration; existing library was not modified");}
 public File root(String sub){File f=new File(context.getFilesDir(),sub);if(!f.isDirectory()&&!f.mkdirs())throw new IllegalStateException("Cannot create private directory");return f;}
 public static String normalize(String in){
  String s=Normalizer.normalize(in==null?"":in,Normalizer.Form.NFKC).toLowerCase(Locale.ROOT);StringBuilder o=new StringBuilder();
  for(int i=0;i<s.length();i++){char c=s.charAt(i);int t=Character.getType(c);if(t==Character.NON_SPACING_MARK||t==Character.COMBINING_SPACING_MARK||c=='\u0640')continue;
   if(c=='\u0622'||c=='\u0623'||c=='\u0625'||c=='\u0671')c='\u0627';if(c=='\u0649')c='\u064a';
   if(c>='\u0660'&&c<='\u0669')c=(char)('0'+c-'\u0660');if(c>='\u06f0'&&c<='\u06f9')c=(char)('0'+c-'\u06f0');o.append(c);
  }return o.toString();
 }
 private static final Set<String> STOP=new HashSet<>(Arrays.asList("what","which","when","where","does","how","the","a","an","is","are","of","to","for","in","on","please","tell","me","about","and","or","ما","ماذا","هو","هي","في","من","عن","الى","كيف","هل","الذي","التي","لي","اريد","اخبرني","مع","و"));
 public static List<String> terms(String q){LinkedHashSet<String> list=new LinkedHashSet<>();Matcher m=Pattern.compile("[\\p{L}\\p{N}]+(?:[-./][\\p{L}\\p{N}]+)*").matcher(normalize(q));while(m.find()&&list.size()<18){String t=m.group();if(t.length()>1&&!STOP.contains(t))list.add(t);}return new ArrayList<>(list);}
 public long count(String sql){try(Cursor c=getReadableDatabase().rawQuery(sql,null)){return c.moveToFirst()?c.getLong(0):0;}}
 public String meta(String key){try(Cursor c=getReadableDatabase().rawQuery("SELECT value FROM meta WHERE key=?",new String[]{key})){return c.moveToFirst()?c.getString(0):"";}}
 public void meta(String key,String value){ContentValues v=new ContentValues();v.put("key",key);v.put("value",value);getWritableDatabase().insertWithOnConflict("meta",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
 public long docByHash(String sha){try(Cursor c=getReadableDatabase().rawQuery("SELECT id FROM docs WHERE sha=?",new String[]{sha})){return c.moveToFirst()?c.getLong(0):-1;}}
 public long addDoc(String name,String sha,int pages,long bytes,String path){ContentValues v=new ContentValues();v.put("name",name);v.put("sha",sha);v.put("pages",pages);v.put("bytes",bytes);v.put("path",path);v.put("created",System.currentTimeMillis());return getWritableDatabase().insertOrThrow("docs",null,v);}
 public long addPage(long doc,int page,String label,String text,float width,float height,JSONArray boxes,boolean ocr){ContentValues v=new ContentValues();v.put("doc",doc);v.put("pageno",page);v.put("label",label);v.put("text",text);v.put("width",width);v.put("height",height);v.put("boxes",boxes.toString());v.put("ocr",ocr?1:0);return getWritableDatabase().insertOrThrow("pages",null,v);}
 public long addChunk(long page,long doc,String text,int vector){if(text.trim().length()<3)return -1;ContentValues v=new ContentValues();v.put("page",page);v.put("doc",doc);v.put("text",text);v.put("vid",vector);long id=getWritableDatabase().insertOrThrow("chunks",null,v);getWritableDatabase().execSQL("INSERT INTO chunks_fts(docid,body) VALUES(?,?)",new Object[]{id,normalize(text)});return id;}
 public void ready(long id,String status){ContentValues v=new ContentValues();v.put("status",status);getWritableDatabase().update("docs",v,"id=?",new String[]{""+id});}
 public void docEnabled(long id,boolean enabled){ContentValues v=new ContentValues();v.put("enabled",enabled?1:0);getWritableDatabase().update("docs",v,"id=?",new String[]{""+id});}
 public void removeDoc(long id){SQLiteDatabase d=getWritableDatabase();String p="";try(Cursor c=d.rawQuery("SELECT path FROM docs WHERE id=?",new String[]{""+id})){if(c.moveToFirst())p=c.getString(0);}d.beginTransaction();try{d.execSQL("DELETE FROM chunks_fts WHERE docid IN (SELECT id FROM chunks WHERE doc=?)",new Object[]{id});d.delete("docs","id=?",new String[]{""+id});d.setTransactionSuccessful();}finally{d.endTransaction();}if(!p.isEmpty()){File f=new File(root("pdf"),p);if(f.isFile()&&!f.delete())throw new IllegalStateException("Index removed, but private PDF copy could not be deleted");}}
 public JSONArray docs()throws JSONException{JSONArray a=new JSONArray();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,name,pages,bytes,enabled,status,(SELECT COUNT(*) FROM chunks WHERE doc=docs.id AND vid<0 AND embedding IS NULL) FROM docs ORDER BY name COLLATE NOCASE",null)){while(c.moveToNext())a.put(new JSONObject().put("id",c.getLong(0)).put("name",c.getString(1)).put("pages",c.getInt(2)).put("bytes",c.getLong(3)).put("enabled",c.getInt(4)==1).put("status",c.getString(5)).put("pending",c.getLong(6)));}return a;}
 public JSONObject page(long id)throws Exception{try(Cursor c=getReadableDatabase().rawQuery("SELECT p.id,p.doc,p.pageno,p.label,p.text,p.width,p.height,p.boxes,p.ocr,d.name,d.path,d.pages,d.enabled FROM pages p JOIN docs d ON d.id=p.doc WHERE p.id=?",new String[]{""+id})){if(!c.moveToFirst())throw new IOException("Source was removed from the library");return new JSONObject().put("id",c.getLong(0)).put("doc",c.getLong(1)).put("pageno",c.getInt(2)).put("label",c.getString(3)).put("text",c.getString(4)).put("width",c.getDouble(5)).put("height",c.getDouble(6)).put("boxes",new JSONArray(c.getString(7))).put("ocr",c.getInt(8)==1).put("name",c.getString(9)).put("path",new File(root("pdf"),c.getString(10)).getAbsolutePath()).put("pages",c.getInt(11)).put("enabled",c.getInt(12)==1);}}
 public long pageId(long doc,int n){try(Cursor c=getReadableDatabase().rawQuery("SELECT id FROM pages WHERE doc=? AND pageno=?",new String[]{""+doc,""+n})){return c.moveToFirst()?c.getLong(0):-1;}}
 public void updateBoxes(long page,JSONArray boxes,float width,float height){ContentValues v=new ContentValues();v.put("boxes",boxes.toString());v.put("width",width);v.put("height",height);getWritableDatabase().update("pages",v,"id=?",new String[]{""+page});}
 public JSONArray models()throws JSONException{JSONArray a=new JSONArray();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,title,path,sha,bytes,enabled,license FROM models ORDER BY bytes",null)){while(c.moveToNext())a.put(new JSONObject().put("id",c.getString(0)).put("title",c.getString(1)).put("path",c.getString(2)).put("sha",c.getString(3)).put("bytes",c.getLong(4)).put("enabled",c.getInt(5)==1).put("license",c.getString(6)));}return a;}
 public void installModel(JSONObject m,File f)throws Exception{ContentValues v=new ContentValues();v.put("id",m.getString("id"));v.put("title",m.getString("title"));v.put("path",f.getAbsolutePath());v.put("sha",m.getString("sha256"));v.put("bytes",m.getLong("bytes"));v.put("license",m.getString("license"));v.put("enabled",0);getWritableDatabase().insertWithOnConflict("models",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
 public void modelEnabled(String id,boolean yes){ContentValues v=new ContentValues();v.put("enabled",yes?1:0);getWritableDatabase().update("models",v,"id=?",new String[]{id});}
 public void removeModel(String id)throws Exception{JSONArray models=models();for(int i=0;i<models.length();i++){JSONObject m=models.getJSONObject(i);if(id.equals(m.getString("id"))){File f=new File(m.getString("path"));if(f.exists()&&!f.delete())throw new IOException("Cannot remove model");getWritableDatabase().delete("models","id=?",new String[]{id});}}}
 public static final class Hit {public long chunk,page,doc;public String text,name,label;public int pageNo;public boolean ocr;public double rank,lexical,semantic;public JSONObject json()throws JSONException{return new JSONObject().put("chunk",chunk).put("page",page).put("doc",doc).put("text",text).put("name",name).put("label",label).put("pageno",pageNo).put("ocr",ocr).put("lexical",lexical).put("semantic",semantic);}}
 private Hit readHit(Cursor c){Hit h=new Hit();h.chunk=c.getLong(0);h.page=c.getLong(1);h.doc=c.getLong(2);h.text=c.getString(3);h.name=c.getString(4);h.pageNo=c.getInt(5);h.label=c.getString(6);h.ocr=c.getInt(7)==1;return h;}
 private static final String HIT_SELECT="SELECT c.id,c.page,c.doc,c.text,d.name,p.pageno,p.label,p.ocr FROM chunks c JOIN docs d ON d.id=c.doc JOIN pages p ON p.id=c.page ";
 public Hit hit(long id){try(Cursor c=getReadableDatabase().rawQuery(HIT_SELECT+"WHERE c.id=? AND d.enabled=1 AND d.status IN ('ready','scanned')",new String[]{""+id})){return c.moveToFirst()?readHit(c):null;}}
 private static double bm25(byte[] bytes){IntBuffer b=ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN).asIntBuffer();int p=b.get(0),cols=b.get(1);double n=Integer.toUnsignedLong(b.get(2));double score=0;for(int ph=0;ph<p;ph++)for(int col=0;col<cols;col++){int o=3+2*cols+(ph*cols+col)*3;double tf=Integer.toUnsignedLong(b.get(o)),df=Integer.toUnsignedLong(b.get(o+2)),avg=Math.max(1,Integer.toUnsignedLong(b.get(3+col))),len=Integer.toUnsignedLong(b.get(3+cols+col));score+=Math.log(1+(n-df+.5)/(df+.5))*tf*2.2/(tf+1.2*(.25+.75*len/avg));}return score;}
 private List<Hit> lexical(String query,long doc){List<String> ts=terms(query);if(ts.isEmpty())return new ArrayList<>();StringBuilder expr=new StringBuilder();for(String t:ts){if(expr.length()>0)expr.append(" OR ");expr.append('"').append(t.replace("\"","")).append('"');}
  String sql="SELECT c.id,c.page,c.doc,c.text,d.name,p.pageno,p.label,p.ocr,matchinfo(chunks_fts,'pcnalx') FROM chunks_fts JOIN chunks c ON c.id=chunks_fts.docid JOIN docs d ON d.id=c.doc JOIN pages p ON p.id=c.page WHERE chunks_fts MATCH ? AND d.enabled=1 AND d.status IN ('ready','scanned')"+(doc>=0?" AND d.id=?":"")+" LIMIT 6000";
  List<Hit> list=new ArrayList<>();String[] args=doc>=0?new String[]{expr.toString(),""+doc}:new String[]{expr.toString()};try(Cursor c=getReadableDatabase().rawQuery(sql,args)){while(c.moveToNext()){Hit h=readHit(c);h.lexical=bm25(c.getBlob(8));String norm=normalize(h.text);int coverage=0;boolean allNumbers=true;for(String t:ts){if(norm.contains(t))coverage++;else if(t.matches(".*[0-9].*"))allNumbers=false;}h.lexical*=.3+.7*coverage/(double)ts.size();if(!allNumbers)h.lexical*=.15;h.rank=h.lexical;list.add(h);}}list.sort((a,b)->Double.compare(b.rank,a.rank));return list.size()>80?new ArrayList<>(list.subList(0,80)):list;
 }
 public List<Hit> search(String query,long doc,float[] embedding)throws Exception{
  List<Hit> lex=lexical(query,doc);Map<Long,Hit> merged=new HashMap<>();for(int i=0;i<lex.size();i++){Hit h=lex.get(i);h.rank=1.0/(60+i);merged.put(h.chunk,h);}
  if(embedding!=null){float[] original=null;File vf=new File(root("semantic"),"vectors.i8"),sf=new File(root("semantic"),"scales.f32");if(vf.isFile()&&sf.isFile())original=NativeEngine.scoreIndex(vf.getAbsolutePath(),sf.getAbsolutePath(),embedding);
   PriorityQueue<double[]> best=new PriorityQueue<>((a,b)->Double.compare(a[1],b[1]));String sql="SELECT c.id,c.vid,c.embedding FROM chunks c JOIN docs d ON d.id=c.doc WHERE d.enabled=1 AND d.status IN ('ready','scanned')"+(doc>=0?" AND d.id=?":"");try(Cursor c=getReadableDatabase().rawQuery(sql,doc>=0?new String[]{""+doc}:null)){while(c.moveToNext()){double sim=-1;int vid=c.getInt(1);if(vid>=0&&original!=null&&vid<original.length)sim=original[vid];else if(!c.isNull(2)){byte[] v=c.getBlob(2);if(v.length==1536){FloatBuffer b=ByteBuffer.wrap(v).order(ByteOrder.LITTLE_ENDIAN).asFloatBuffer();sim=0;for(int k=0;k<384;k++)sim+=embedding[k]*b.get(k);}}if(sim>=.72){best.offer(new double[]{c.getLong(0),sim});if(best.size()>80)best.poll();}}}
   ArrayList<double[]> sem=new ArrayList<>(best);sem.sort((a,b)->Double.compare(b[1],a[1]));for(int i=0;i<sem.size();i++){long id=(long)sem.get(i)[0];Hit h=merged.get(id);if(h==null){h=hit(id);if(h==null)continue;merged.put(id,h);}h.semantic=sem.get(i)[1];h.rank+=1.0/(60+i);}
  }
  ArrayList<Hit> list=new ArrayList<>(merged.values());list.sort((a,b)->Double.compare(b.rank,a.rank));ArrayList<Hit> unique=new ArrayList<>();Set<Long> pages=new HashSet<>();for(Hit h:list){if(!pages.add(h.page))continue;unique.add(h);if(unique.size()>=12)break;}return unique;
 }
 public void putEmbedding(long id,float[] v){ByteBuffer b=ByteBuffer.allocate(1536).order(ByteOrder.LITTLE_ENDIAN);for(float x:v)b.putFloat(x);ContentValues c=new ContentValues();c.put("embedding",b.array());getWritableDatabase().update("chunks",c,"id=?",new String[]{""+id});}
 public JSONArray pending(long doc,int limit)throws JSONException{JSONArray a=new JSONArray();String sql="SELECT c.id,c.text FROM chunks c JOIN docs d ON d.id=c.doc WHERE c.vid<0 AND c.embedding IS NULL AND d.enabled=1 AND d.status='ready'"+(doc>=0?" AND d.id=?":"")+" LIMIT "+Math.max(1,Math.min(128,limit));try(Cursor c=getReadableDatabase().rawQuery(sql,doc>=0?new String[]{""+doc}:null)){while(c.moveToNext())a.put(new JSONObject().put("id",c.getLong(0)).put("text",c.getString(1)));}return a;}
 public void saveHistory(String question,String payload){ContentValues v=new ContentValues();v.put("question",question);v.put("payload",payload);v.put("created",System.currentTimeMillis());getWritableDatabase().insert("history",null,v);getWritableDatabase().execSQL("DELETE FROM history WHERE id NOT IN (SELECT id FROM history ORDER BY id DESC LIMIT 100)");}
 public JSONArray history()throws JSONException{JSONArray a=new JSONArray();try(Cursor c=getReadableDatabase().rawQuery("SELECT question,payload,created FROM history ORDER BY id DESC LIMIT 100",null)){while(c.moveToNext())a.put(new JSONObject().put("question",c.getString(0)).put("payload",c.getString(1)).put("created",c.getLong(2)));}return a;}
 public static String sha(File f)throws Exception{MessageDigest m=MessageDigest.getInstance("SHA-256");try(InputStream in=new FileInputStream(f)){byte[] b=new byte[1024*1024];int n;while((n=in.read(b))!=-1)m.update(b,0,n);}StringBuilder s=new StringBuilder();for(byte b:m.digest())s.append(String.format(Locale.ROOT,"%02x",b&255));return s.toString();}
 public static String read(InputStream in,int limit)throws IOException{try(InputStream r=in;ByteArrayOutputStream o=new ByteArrayOutputStream()){byte[] b=new byte[16384];int n;while((n=r.read(b))!=-1){if(o.size()+n>limit)throw new IOException("Input exceeds safe size");o.write(b,0,n);}return new String(o.toByteArray(),StandardCharsets.UTF_8);}}
}
